// Generated by nuxt-seo-utils
declare module '#app' {
  import { HeadEntry, HeadTag } from '@unhead/vue/types'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}
declare module '@unhead/schema' {

  type PublicFiles = '/_robots.txt' | '/android-chrome-192x192.png' | '/android-chrome-512x512.png' | '/apple-touch-icon.png' | '/favicon-16x16.png' | '/favicon-32x32.png' | '/favicon.ico' | '/site.webmanifest' | '/img/works/work-1.jpg' | '/img/works/work-10.jpg' | '/img/works/work-11.jpg' | '/img/works/work-12.jpg' | '/img/works/work-13.jpg' | '/img/works/work-14.jpg' | '/img/works/work-15.jpg' | '/img/works/work-16.jpg' | '/img/works/work-17.jpg' | '/img/works/work-18.jpg' | '/img/works/work-19.jpg' | '/img/works/work-2.jpg' | '/img/works/work-20.jpg' | '/img/works/work-21.jpg' | '/img/works/work-22.jpg' | '/img/works/work-23.jpg' | '/img/works/work-24.jpg' | '/img/works/work-25.jpg' | '/img/works/work-26.jpg' | '/img/works/work-27.jpg' | '/img/works/work-28.jpg' | '/img/works/work-29.jpg' | '/img/works/work-3.jpg' | '/img/works/work-30.jpg' | '/img/works/work-31.jpg' | '/img/works/work-32.jpg' | '/img/works/work-33.jpg' | '/img/works/work-34.jpg' | '/img/works/work-35.jpg' | '/img/works/work-36.jpg' | '/img/works/work-37.jpg' | '/img/works/work-38.jpg' | '/img/works/work-39.jpg' | '/img/works/work-4.jpg' | '/img/works/work-40.jpg' | '/img/works/work-5.jpg' | '/img/works/work-6.jpg' | '/img/works/work-7.jpg' | '/img/works/work-8.jpg' | '/img/works/work-9.jpg' | (string & Record<never, never>)
  type JsFiles = (string & Record<never, never>)

  interface SchemaAugmentations {
    link: import('@unhead/schema').UserTagConfigWithoutInnerContent & {
      href: PublicFiles
    }
    script: import('@unhead/schema').TagUserProperties & {
      src: JsFiles
    }
  }
}

export {}
