// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/17/2026, 11:11:21 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/mac/Downloads/klassmec/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Downloads/klassmec/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Downloads/klassmec/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Downloads/klassmec/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Downloads/klassmec/plugins/**/*.{js,ts,mjs}","/Users/mac/Downloads/klassmec/composables/**/*.{js,ts,mjs}","/Users/mac/Downloads/klassmec/utils/**/*.{js,ts,mjs}","/Users/mac/Downloads/klassmec/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Downloads/klassmec/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Downloads/klassmec/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Downloads/klassmec/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;